# -*- coding: utf-8 -*-
"""Copy of Berat dan Tinggi Badan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XT4Q7AqFXvr2sZ3fh8qoNZBRxhGONhOk

# Klasifikasi Berat Badan dan Tinggi Badan
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
import joblib

df2 = pd.read_excel("https://github.com/ruhe09/tugas/blob/tugas_sql/weight-height.xlsx?raw=true")
new_header = ['Gender,Weight,Height'] 
df=df2.to_csv('perbarui.csv', header=new_header,index=False,sep=';')

df2

df2=pd.read_csv('perbarui.csv')
df2

df = pd.read_csv('https://github.com/ruhe09/tugas/blob/tugas_sql/dataset.csv?raw=true')
df

df.head()

"""## Scaling dan Labeling Atribut"""

std_scaler = StandardScaler()
label_enc = LabelEncoder()
df.Gender = label_enc.fit_transform(df.Gender)
df.iloc[:, :-1] = std_scaler.fit_transform(df.iloc[:, :-1])

df.head()

X = df.iloc[:, :-1]
X

y = df.iloc[:, -1]
y

"""## Training Model"""

lin_regr = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y)

model = lin_regr.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

print(f"Akurasi Model: {accuracy * 100}%")

"""## Menyimpan Model dan Scaler"""

joblib.dump((model, std_scaler), "berat_badan.pkl")