# Generated by Django 3.2.8 on 2022-06-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0002_auto_20220601_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
