# Generated by Django 3.2.8 on 2022-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=11, verbose_name='phone number'),
        ),
    ]
