# Generated by Django 3.2.8 on 2022-05-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0005_auto_20220529_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
