# Generated by Django 3.2.8 on 2022-05-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0006_alter_users_user_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='Cv_Model',
        ),
    ]
