# Generated by Django 3.2.8 on 2022-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0007_auto_20220604_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=16, verbose_name='phone number'),
        ),
    ]
