# Generated by Django 3.2.8 on 2022-06-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buset', '0008_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunga_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
